version: '3'

services:
   platform:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 8080:8080
      networks:
         - platformNetwork
      restart: always

networks:
   platformNetwork:
