export enum AuthSource {
	EMAIL = 'email',
	GOOGLE = 'google',
	FACEBOOK = 'facebook',
	TRUECALLER = "truecaller",
	META_MASK = 'metaMask',
}

export enum BLOCKCHAIN_TYPES {
	AVAX = 'AVAX',
	WBET = 'WBET',
}

export enum BALANCE_TYPE {
	BLOCK_CHAIN = 'blockChain',
	REFERRAL = 'referral',
}

export const otpCount = 6 as const;

export const developmentOtp = '123456' as const;

export const dummyGamesUrl = [
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb1.png',
		url_background: 'https://picture-hosting.com/blackjack/bg1.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 1',
		game_id: 615,
		game_code: 'ont_blackjackclassic1',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-05',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb2.png',
		url_background: 'https://picture-hosting.com/blackjack/bg2.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 2',
		game_id: 616,
		game_code: 'ont_blackjackclassic2',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-06',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb3.png',
		url_background: 'https://picture-hosting.com/blackjack/bg3.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 3',
		game_id: 617,
		game_code: 'ont_blackjackclassic3',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-07',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb4.png',
		url_background: 'https://picture-hosting.com/blackjack/bg4.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 4',
		game_id: 618,
		game_code: 'ont_blackjackclassic4',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-08',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb5.png',
		url_background: 'https://picture-hosting.com/blackjack/bg5.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 5',
		game_id: 619,
		game_code: 'ont_blackjackclassic5',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-09',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb6.png',
		url_background: 'https://picture-hosting.com/blackjack/bg6.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 6',
		game_id: 620,
		game_code: 'ont_blackjackclassic6',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-10',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb7.png',
		url_background: 'https://picture-hosting.com/blackjack/bg7.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 7',
		game_id: 621,
		game_code: 'ont_blackjackclassic7',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-11',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb8.png',
		url_background: 'https://picture-hosting.com/blackjack/bg8.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 8',
		game_id: 622,
		game_code: 'ont_blackjackclassic8',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-12',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb9.png',
		url_background: 'https://picture-hosting.com/blackjack/bg9.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 9',
		game_id: 623,
		game_code: 'ont_blackjackclassic9',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-13',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
	{
		url_thumb: 'https://picture-hosting.com/blackjack/thumb10.png',
		url_background: 'https://picture-hosting.com/blackjack/bg10.png',
		product: 'OneTouch',
		platforms: ['GPL_DESKTOP', 'GPL_MOBILE'],
		name: 'Blackjack Classic 10',
		game_id: 624,
		game_code: 'ont_blackjackclassic10',
		freebet_support: true,
		enabled: true,
		category: 'Blackjack',
		blocked_countries: ['AU', 'US', 'UK'],
		release_date: '2017-11-14',
		scatters: false,
		in_game_freebets: false,
		volatility: 1,
		rtp: '98.8',
		paylines: 0,
		hit_ratio: '45.50',
		certifications: ['CURACAO', 'MGA'],
		languages: ['eng', 'jpn', 'kor', 'deu'],
		theme: ['Vegas', 'Blue', 'Wood'],
		technology: ['HTML5'],
	},
];
